name: build-lalapad

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/build.yml"
      - "firmware/**"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git cmake ninja-build gperf ccache dfu-util \
            device-tree-compiler wget python3-pip
          pip3 install --upgrade pip
          pip3 install west

      # ← ここがポイント：ZMK公式マニフェストで west ワークスペースを作る
      - name: Fetch ZMK
        run: |
          set -e
          rm -rf zmk build || true
          west init -m https://github.com/zmkfirmware/zmk.git zmk
          cd zmk
          west update
          west zephyr-export

      - name: Build right
        run: |
          set -e
          mkdir -p output
          cd zmk
          west build -s app -d build/right -b seeeduino_xiao_ble -- \
            -DZMK_CONFIG="$GITHUB_WORKSPACE/firmware/config"
          cp build/right/zephyr/zmk.uf2 "$GITHUB_WORKSPACE/output/LalaPad_right.uf2"

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: LalaPad_right_firmware
          path: output/LalaPad_right.uf2
